import FWCore.ParameterSet.Config as cms
from HiggsAnalysis.HiggsTo2photons.hggPhotonIDCuts_cfi import *
#from PhysicsTools.SelectorUtils.pfJetIDSelector_cfi import pfJetIDSelector
#from CMGTools.External.pujetidproducer_cfi import stdalgos, chsalgos

ggNtuplizer = cms.EDAnalyzer("ggNtuplizer",
                             hggPhotonIDConfiguration = hggPhotonIDCuts,
                             doGenParticles   = cms.bool(True),
                             runOnParticleGun = cms.bool(False),
                             dumpPhotons      = cms.bool(True), 
                             dumpJets         = cms.bool(False),
                             dumpSubJets      = cms.bool(False),
                             dumpTaus         = cms.bool(False),
                             isAOD            = cms.bool(False), #### actually configured through run_data_74x.py
                             runHFElectrons   = cms.bool(False),
                             runphoIDVID      = cms.bool(True),
                             runeleIDVID      = cms.bool(True),
                             runphoMVAID      = cms.bool(False),
                             runeleMVAID      = cms.bool(False),
                             development      = cms.bool(False),
                             addFilterInfoAOD = cms.bool(False),
                             addFilterInfoMINIAOD = cms.bool(True),
                             doNoHFMET            = cms.bool(False),

                             trgFilterDeltaPtCut = cms.double(0.5),
                             trgFilterDeltaRCut  = cms.double(0.3),

                             triggerEvent      = cms.InputTag("selectedPatTrigger", "", ""),
                             triggerResults    = cms.InputTag("TriggerResults", "", "HLT"),
                             #patTriggerResults = cms.InputTag("TriggerResults", "", "PAT"),
                             patTriggerResults = cms.InputTag("TriggerResults", "", "RECO"),
                             genParticleSrc    = cms.InputTag("prunedGenParticles"),
                             generatorLabel    = cms.InputTag("generator"),
                             newParticles      = cms.vint32(4000011, 4000013, 1000006, 1000022, 1000024, 1000025, 35),
                             pileupCollection  = cms.InputTag("slimmedAddPileupInfo"),
                             VtxLabel          = cms.InputTag("offlineSlimmedPrimaryVertices"),
                             VtxBSLabel        = cms.InputTag("offlinePrimaryVerticesWithBS"),
                             rhoLabel          = cms.InputTag("fixedGridRhoFastjetAll"),
                             rhoCentralLabel   = cms.InputTag("fixedGridRhoFastjetCentralNeutral"),
                             pfMETLabel        = cms.InputTag("slimmedMETs"),
                             electronSrc       = cms.InputTag("slimmedElectrons"),
                             photonSrc         = cms.InputTag("slimmedPhotons"),
                             muonSrc           = cms.InputTag("slimmedMuons"),
                             gsfTrackSrc       = cms.InputTag("electronGsfTracks"),
                             ebReducedRecHitCollection = cms.InputTag("reducedEgamma", "reducedEBRecHits"),
                             eeReducedRecHitCollection = cms.InputTag("reducedEgamma", "reducedEERecHits"),
                             esReducedRecHitCollection = cms.InputTag("reducedEgamma", "reducedESRecHits"),
                             recoPhotonSrc             = cms.InputTag("reducedEgamma", "reducedGedPhotonCores"),
                             TrackLabel                = cms.InputTag("generalTracks"),
                             gsfElectronLabel          = cms.InputTag("gsfElectrons"),
                             PFAllCandidates           = cms.InputTag("particleFlow"),
                             ak4JetSrc                 = cms.InputTag("slimmedJets"),
                             ak8JetSrc                 = cms.InputTag("slimmedJetsAK8"),
                             tauSrc                    = cms.InputTag("slimmedTaus"),
                             #pfLooseId                 = pfJetIDSelector.clone(),

                             phoLooseIdMap = cms.InputTag("egmPhotonIDs:cutBasedPhotonID-Spring15-50ns-V1-standalone-loose"),
                             phoMediumIdMap = cms.InputTag("egmPhotonIDs:cutBasedPhotonID-Spring15-50ns-V1-standalone-medium"),
                             phoTightIdMap = cms.InputTag("egmPhotonIDs:cutBasedPhotonID-Spring15-50ns-V1-standalone-tight"),
                             phoMVAValuesMap = cms.InputTag("photonMVAValueMapProducer:PhotonMVAEstimatorRun2Spring15NonTrig25nsV2Values"),
                             phoChargedIsolation       = cms.InputTag("photonIDValueMapProducer:phoChargedIsolation"),
                             phoNeutralHadronIsolation = cms.InputTag("photonIDValueMapProducer:phoNeutralHadronIsolation"),
                             phoPhotonIsolation        = cms.InputTag("photonIDValueMapProducer:phoPhotonIsolation"),
                             phoWorstChargedIsolation  = cms.InputTag("photonIDValueMapProducer:phoWorstChargedIsolation"),
                             packedPFCands   = cms.InputTag("packedPFCandidates"),
                             eleVetoIdMap    = cms.InputTag("egmGsfElectronIDs:cutBasedElectronID-Spring15-25ns-V1-standalone-veto"),
                             eleLooseIdMap   = cms.InputTag("egmGsfElectronIDs:cutBasedElectronID-Spring15-25ns-V1-standalone-loose"),
                             eleMediumIdMap  = cms.InputTag("egmGsfElectronIDs:cutBasedElectronID-Spring15-25ns-V1-standalone-medium"),
                             eleTightIdMap   = cms.InputTag("egmGsfElectronIDs:cutBasedElectronID-Spring15-25ns-V1-standalone-tight"),
                             eleHEEPIdMap    = cms.InputTag("egmGsfElectronIDs:heepElectronID-HEEPV60"),
                             eleNonTrgMVAValuesMap = cms.InputTag("electronMVAValueMapProducer:ElectronMVAEstimatorRun2Spring15NonTrig25nsV1Values"),
                             eleTrgMVAValuesMap = cms.InputTag("electronMVAValueMapProducer:ElectronMVAEstimatorRun2Spring15Trig25nsV1Values")
)
